spring:
  datasource:
    url: jdbc:mysql://192.168.184.24:3306/store
    username: root
    password: 123123
  banner:
    location: banner.txt

mybatis:
  mapper-locations: classpath:mapper/*.xml
#properties里写法：mybatis.mapper-locations=classpath:mapper/*.xml