spring:
  datasource:
    url: jdbc:mysql://192.168.184.24:3306/store
    username: root
    password: 123123
  banner:
    location: banner.txt
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      整个请求的大小15MB，包含文件的10MB
#      max-request-size: 15MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
#properties里写法：mybatis.mapper-locations=classpath:mapper/*.xml
